# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Derogation
                                 A QGIS plugin
 ce plugin  est conçu pour aider les utilisateurs à évaluer si un projet de dérogation est favorable ou non dans la ville de Khémisset, au Maroc.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-06-02
        copyright            : (C) 2024 by ibtissam
        email                : e.btissam.elbakali@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Derogation class from file Derogation.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Derogation import Derogation
    return Derogation(iface)
